### ISSUE TITLE
The stpyvista app crashes

### ISSUE THREAD

**Issue by suchanek** [edsaac/stpyvista-tests#4]
That is all. I got an 'uhoh' message. MacBook Pro with Sonoma 14.2, Safari Version 17.2 (19617.1.11.11.3).

Cheers, and thanks for the great framework!

**Comment by edsaac** [comment]
Got it, I restarted it and it should be up and running now. Do you remember in what specific page it broke?

**Comment by suchanek** [comment]
I don't, so I'll close this one. thanks though!
